### ISSUE TITLE
issue in macos:  WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. 

### ISSUE THREAD

**Issue by Darkcast** [d78ui98/APKDeepLens#8]
Running on macos M1 arm

```
[+] /Users/nimrod/gitapps/APKDeepLens/base.apk found!
[+] Creating new directory for extracting apk : /Users/nimrod/gitapps/APKDeepLens/app_source/base.apk
[+] Extracting the source code to : /Users/nimrod/gitapps/APKDeepLens/app_source/base.apk
INFO  - loading ...
INFO  - processing ...
2024-03-12 11:49:41.559 java[6738:1798207] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
ERROR - Error saving class: androidx.datastore.migrations.SharedPreferencesMigration
jadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: androidx.datastore.migrations.SharedPreferencesMigration
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:93)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:253)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:218)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$4(JadxDecompiler.java:257)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Codegen failed
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:89)
	... 7 common frames omitted
ERROR - Error saving class: kotlinx.coroutines.flow.FlowKt__ShareKt$launchSharing$1
jadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: kotlinx.coroutines.flow.FlowKt__ShareKt$launchSharing$1
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:93)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:253)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:218)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$4(JadxDecompiler.java:257)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Codegen failed
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:89)
	... 7 common frames omitted
ERROR - finished with errors, count: 18
CompletedProcess(args=['/Users/nimrod/gitapps/APKDeepLens/static_tools/jadx/bin/jadx', '/Users/nimrod/gitapps/APKDeepLens/base.apk', '-d', '/Users/nimrod/gitapps/APKDeepLens/app_source/base.apk'], returncode=0)
jad
```
Jadx installed 
```
jadx --version
1.4.7
```

**Comment by d78ui98** [comment]
Hello @Darkcast 
Thank you for reporting this. This issue is because of Jadx's limitations, as it cannot guarantee 100% successful decompilation of code, and errors can occur as a result. This limitation is acknowledged in  Troubleshooting Q&A page in jadx. You can find more details here: [Troubleshooting Q&A - Decompilation Issues](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A#decompilation-issues).
